### ISSUE TITLE
Gloomrot Update

### ISSUE THREAD

**Issue by Herkdess** [molenzwiebel/Wetstone#11]
As expected, this mod doesn't works on gloomrot update, i wanted to know if there will be any updates on this?

**Comment by molenzwiebel** [comment]
I am no longer active in VRising modding. @decaprime has access to this repository and the Thunderstore deployment, hopefully he will find time to update.

**Comment by decaprime** [comment]
It's being worked on in #12

I'm curious what developers need from this update for specifically, as it could inform validation of his PR. Which features are you working on and how are you blocked from current development? Otherwise I assume folks are looking for this because they had it installed previously as a dependency of a different mod they use to use. I call this out because there are some mods that 'depend' on Wetstone just for Reload or a call to get the Server world and should be able to be unblocked before this publishes to Thunderstore.

**Comment by MrJoshua023** [comment]
I'm betting most are like myself where mods are failing because they depend on this.  
I myself grabbed 3 'popular' mods that all depend on this dependency.  So I can't say what is needed exactly.

Sample error line from the mod loader before it crashes out.
[Error  :   BepInEx] Error loading [Wetstone 1.2.0]: System.TypeLoadException: Failure has occurred while loading a type.
  at Wetstone.WetstonePlugin.Load () [0x00018] in <d6ea8adf186546afb7e37a3f9b415208>:0
  at BepInEx.IL2CPP.IL2CPPChainloader.LoadPlugin (BepInEx.PluginInfo pluginInfo, System.Reflection.Assembly pluginAssembly) [0x00011] in <20831d408969472ba3d48658d4a1512f>:0
  at BepInEx.Bootstrap.BaseChainloader`1[TPlugin].Execute () [0x00284] in <91aaa8349151457a98c04caf9728bc52>:0

**Comment by Kreldin** [comment]
Hi. Came here for the same issue as the above user. I know basically nothing about V-Rising modding, only that the mods I was trying to use are all dependent on this. (Specifically, HuntControl, ModernCamera, and RPGMods)

**Comment by AnsgarTOdinson** [comment]
Same issue as all above.  Pretty much all my mods are borked without this one.

**Comment by MrJoshua023** [comment]
Hi decaprime.  Looks like we may be jumping the gun here on you, I think because then bepinexpack is always assumed to be working... but it seems that is the problem currently.  To test myself, I ran v rising with only bepin enabld and nothing else, still crashed.
https://github.com/BepInEx/BepInEx/issues/615

Though it looks like you're already aware and have your own experimental release.
https://github.com/decaprime/VRising-Modding/releases/tag/0.668.001

**Comment by Kreldin** [comment]
Hello Decaprime, thanks for the reply. 
Thunderstore, for some reason, believes that all three mods require Wetstone, and in fact, won't allow them to be enabled without it. Disabling Wetstone forcibly disables all three mods.

Unfortunately, I don't really know enough about modding to be able to install them manually to try them without it to see if they work despite the update. Since they're not updated either, probably best for me to just wait a while and try again when y'all manage to get Wetstone updated to solve whatever'c causing the crash, and possibly give them time to update too.

Anyway, thank you for the reply, and your work on fixing Wetstone, (even if I don't know what it's for, lol).

Have a wonderful day. =^.^=

**Comment by decaprime** [comment]
Thanks for detailing that for me @Kreldin , I was unaware. #12 has been merged so I'm closing this issue.

Also thanks for the link to that issue @MrJoshua023, I'll make sure we have the info over there too
